### ISSUE TITLE
Import calendar to Home Assistant

### ISSUE THREAD

**Issue by cvc90** [nixxo/nixxo.github.io#5]
Hi @nixxo,

I'm trying to import your calendar into Home Assistant and I'm getting some errors, could you help me import it? 

I've tried other calendars, like MotoTiming, and they work fine.

![Image](https://github.com/user-attachments/assets/f612b8ba-a243-42bd-a6fc-f7168f38f451)

Thanks

**Comment by nixxo** [comment]
Thank for using my calendars.

Or at least trying to... 😅 

It should be fixed now. Give it a try and let me know.

**Comment by cvc90** [comment]
Hi @nixxo,

I just tried it and I'm still getting the same errors.

I think it has something to do with the multiple time windows the calendar has, because comparing it to others, that's the only thing I see that's different.

Thanks

**Comment by nixxo** [comment]
Can you enable some sort of "debug mode" in the software you are using to have a more detailed log?

I'm not familiar with the Home Assistant ecosystem, it seems to use this component to handle ics calendars: https://github.com/franc6/ics_calendar

If this is the case, in the readme there it's indicated that is possible to choose a different PARSER to read and decode the ics file. Maybe try doing that.


In the latest updates to the calendar i fixed an issue on my side and now tha calendar are compliant with the iCal standard https://icalendar.org/validator.html?url=https://nixxo.github.io/calendars/motogp/2025/MotoGP_2025_calendar.ics which I thought was the error that triggered your software to not load the calendar. Evidently I was wrong.

To summarize:
- Can you provide info an the specific calendar you are using?
- More detailed log from Home assistant if possible
- Change PARSER config inside the ics module of Home assistant

**Comment by cvc90** [comment]
Hi @nixxo 

I'm testing with the MotoGP calendar (All sessions).

I'm using the ics_calendar integration to import the calendar.

I'll try changing the parse from .ics to .rie (but I don't think that's the problem).

I'll try to see if there's a debugging method that provides more information so you can debug the error.

I'll update this comment as soon as I have more information.

**Comment by nixxo** [comment]
Installed home assistant and testing...

![Image](https://github.com/user-attachments/assets/e8360191-f9cc-497b-9b3f-5347b7b9ea66)

**Comment by nixxo** [comment]
Ok, @cvc90 try this test calendar url: https://raw.githubusercontent.com/nixxo/nixxo.github.io/9edcca0454706bd83780d392dca1acc3ecfad9c2/calendars/motogp/2025/MotoGP_2025_calendar.ics

it should work, it works in my installation of home assistant.

Check also, if it loads, if the timezone conversion is ok.

**Comment by cvc90** [comment]
Great work! 

I just tested it and can confirm that it now loads without problems and doesn't seem to give any registration errors.

The times seem to load correctly

Here's a sample of how an event is displayed with your calendar and another with MotoTiming's.

![Image](https://github.com/user-attachments/assets/ca59a885-e5a3-40ed-a5d2-55361f16450c)

![Image](https://github.com/user-attachments/assets/5724db02-fa3b-49f0-9a24-dd28a73e5111)

Do you know if it's possible to separate the description by lines?

It would help to provide a clearer and more precise description.

I believe Home Assistant supports HTML code; perhaps simply adding a line break (br) would be possible?

I also see that you've installed Home Assistant, be careful, you're entering a world that's difficult to escape 😄

If you need any help, let me know.

**Comment by nixxo** [comment]
I updated the official calendars with the fix for the reported import problem. You can now ditch the test url calendar provided and use the standard url.

I did a little test and it does not seems to support HTML, at least it displayed the text as before. I'll do more tests when I have more time

**Comment by cvc90** [comment]
Thank you for the work done, everything is working properly now.
